<?php
require __DIR__.'/includes/layout.php';
$id=(int)($_GET['id']??0);
$columns=[]; foreach(['PriceDescr','OrderAllow'] as $c){$columns[$c]=column_exists('csSoftProducts',$c);} 
$groups=db()->query('SELECT ID,Name FROM csSoftGroups ORDER BY Name')->fetchAll();
$row=['SoftGroupID'=>'','Name'=>'','ShortDescr'=>'','About'=>'','Features'=>'','IsActive'=>1,'OrderAllow'=>0,'PriceDescr'=>''];
if($id){$q=db()->prepare('SELECT * FROM csSoftProducts WHERE ID=?');$q->execute([$id]);$row=$q->fetch()?:$row;}
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$data=[(int)$_POST['group'],$_POST['name']??'',$_POST['shortDescr']??'',$_POST['about']??'',$_POST['features']??'',isset($_POST['active'])?1:0];if($id){$sql='UPDATE csSoftProducts SET SoftGroupID=?,Name=?,ShortDescr=?,About=?,Features=?,IsActive=? WHERE ID=?';$data[]=$id;db()->prepare($sql)->execute($data);}else{$sql='INSERT INTO csSoftProducts (SoftGroupID,Name,ShortDescr,About,Features,IsActive) VALUES (?,?,?,?,?,?)';db()->prepare($sql)->execute($data);$id=(int)db()->lastInsertId();}redirect('product-edit.php?id='.$id);}
admin_header($id?'Редактирование продукта':'Новый продукт');
?><div class="card"><form method="post"><input type="hidden" name="_csrf" value="<?=aesc(csrf_token())?>"><div class="form-grid"><div class="field"><label class="label">Название</label><input class="input" name="name" required value="<?=aesc(a_legacy($row['Name']??''))?>"></div><div class="field"><label class="label">Группа</label><select class="select" name="group" required><?php foreach($groups as $g): ?><option value="<?=$g['ID']?>" <?=$row['SoftGroupID']==$g['ID']?'selected':''?>><?=aesc(a_legacy($g['Name']))?></option><?php endforeach; ?></select><div class="help">Группа видна только в админке.</div></div><div class="field full"><label class="label">Краткое описание</label><textarea class="textarea" name="shortDescr" rows="3"><?=aesc(a_legacy($row['ShortDescr']??''))?></textarea></div><div class="field full"><label class="label">О программе</label><textarea class="textarea" name="about" rows="10"><?=aesc(a_legacy($row['About']??''))?></textarea></div><div class="field full"><label class="label">Возможности</label><textarea class="textarea" name="features" rows="8"><?=aesc(a_legacy($row['Features']??''))?></textarea></div><div class="field"><label class="checkbox"><input type="checkbox" name="active" <?=$row['IsActive']?'checked':''?>> Активен на сайте</label></div></div><div class="actions" style="margin-top:20px"><button class="btn primary">Сохранить</button><a class="btn" href="products.php">Отмена</a><?php if($id): ?><a class="btn" href="product-assets.php?id=<?=$id?>">Файлы, скриншоты и цены</a><?php endif; ?></div></form></div><?php admin_footer();
